"""Submit EWE concept v5 to the 4-phase review board.

v5 addresses the 5 required modifications from v4:
  C1 — STOCHASTIC_COUPLING as a 5th ECP class, with Itô
       isometry postcondition, filtration consistency, and
       noise-type declaration; the decision tree grows a
       Q5 branch before the UNCLASSIFIED escape hatch.
  C2 — Non-hyperbolic fixed-point protocol: explicit
       NONHYPERBOLIC_INCONCLUSIVE status when the Jacobian
       spectrum has any zero or pure-imaginary eigenvalue,
       requiring a Lyapunov function or center-manifold
       certificate before upgrading to VERIFIED.
  C3 — Tensor rank consistency: DOV-DSL dimensional checking
       is declared scalar-unit-only; a separate
       tensor_rank_consistency obligation records rank, index
       symmetry, and contraction validity for tensor-valued
       exchanges. FSI stress-tensor example is walked through.
  C4 — Exhaustiveness claim downgraded from 'constructive
       proof' to 'pragmatically complete partition with
       explicit escape hatch': Q4-NO terminal renamed from
       REJECTED to UNCLASSIFIED with a structured schema
       (free-form description, mandatory human review flag,
       optional reduction argument). The word 'proof' is
       removed from the exhaustiveness discussion.
  C5 — Modulated Dirac singularity sets: architect-declared
       `singularities` field, either excluded from the
       verification domain with justification or with
       explicit verification of behavior at those points.
       Numerical fallback must not silently pass over them.
Plus: pde_kinetic_annex convergence obligation marked as
  human-verified, not validator-enforced.
"""

from __future__ import annotations

import sys
from pathlib import Path

_LABS_V2 = Path(__file__).resolve().parent.parent
if str(_LABS_V2) not in sys.path:
    sys.path.insert(0, str(_LABS_V2))

from framework.ai_consensus import (
    AIConsensusBoard,
    DESIGN_RUBRIC_SCHEMA,
    DESIGN_REVIEW_PERSONAS,
)
from framework.ai_review_board import AIBoardKeysMissing

REVIEW_PATH = _LABS_V2 / "cross_analysis" / "EWE_CONCEPT_REVIEW_V5.md"


_CONCEPT_V5 = """\
# EWE Concept v5 — Board Review

## Context
v4 was reviewed by the 4-phase board. Editor verdict: MODIFY.
All four reviewers responded. Substantive convergence: all four
MODIFY with rubric means 4.20–4.40, independently converging on
the same five technical gaps. v5 addresses each below.
Everything from v4 not listed here is unchanged.

---

## C1 — STOCHASTIC_COUPLING as the fifth ECP class

**Problem (v4):** Shared Brownian motion W(t) across two SDEs
is not a conserved quantity, not algebraic closure, not
power-conserving, and not a rate term in the C¹ sense. Itô
sample paths are semimartingales, not C¹; calling them
RATE_COUPLING is a category error (the postcondition assumes
C¹ right-hand sides). All four reviewers in v4 flagged this.
The v4 submission raised it as a question without resolving
it — honest but insufficient for schema lockdown.

**v5 resolution — add STOCHASTIC_COUPLING with Itô-aware
postconditions:**

```yaml
composition_class: STOCHASTIC_COUPLING
noise_type: additive | multiplicative | correlated
noise_calculus: ito | stratonovich
filtration:
  shared_sigma_algebra: "F_t generated by (W_1(s), W_2(s))_{s<=t}"
  adapted: true               # both SDEs must be F_t-adapted
ito_isometry_postcondition:
  statement: |
    E[(∫_0^T H_s dW_s)^2] = E[∫_0^T H_s^2 ds]
    must hold for every square-integrable integrand H
    appearing in eq_a or eq_b's diffusion term.
  verification: symbolic_moment_check
  result: VERIFIED             # or UNVERIFIED_SYMBOLICALLY
correlation_matrix:
  form: "Matrix([[1, rho], [rho, 1]])"
  positive_semidefinite: true
regularity:
  drift_lipschitz: true        # SDE existence-uniqueness
  diffusion_lipschitz: true
```

**Pre-conditions:**
- At least one state equation in the composition has a
  non-trivial diffusion term (not a degenerate SDE).
- The noise process is well-defined on a common filtered
  probability space (Ω, F, {F_t}, P).
- The noise calculus (Itô vs Stratonovich) is declared
  uniformly across all equations in the composition.

**Post-conditions:**
- Itô isometry holds for all square-integrable integrands in
  the diffusion terms (checked symbolically where possible,
  numerically by Monte Carlo sampling as fallback).
- The correlation matrix of the driving noise is
  positive-semidefinite.
- Drift and diffusion coefficients are globally Lipschitz
  (strong uniqueness) OR an explicit weak-solution framework
  is declared with its own regularity conditions.
- Mixed calculi are rejected at ingest — a composition cannot
  partially use Itô and partially use Stratonovich without an
  explicit Wong-Zakai conversion record.

**Decision tree insertion (between Q4 and the escape hatch):**

```
Q4: RATE_COUPLING with C¹ right-hand sides? → RATE_COUPLING
Q5: Shared stochastic driving noise (SDE diffusion terms)?
    YES → STOCHASTIC_COUPLING
    NO  → UNCLASSIFIED  (see C4)
```

**Citation:** Øksendal, *Stochastic Differential Equations*
6th ed., §3–4 (Itô isometry) and §5 (existence-uniqueness);
Protter, *Stochastic Integration and Differential Equations*,
2nd ed., Ch V (semimartingale framework).

---

## C2 — Non-hyperbolic fixed-point protocol

**Problem (v4):** The RATE_COUPLING example in v4's own C1
text (Lotka-Volterra coexistence point) has pure-imaginary
eigenvalues, making it non-hyperbolic. v4 allowed
linearization alone to label this "center" — but
linearization is inconclusive for centers, and every
reviewer flagged this.

**v5 resolution — explicit NONHYPERBOLIC_INCONCLUSIVE status:**

```yaml
stability_protocol:
  declared_fixed_points:
    - label: "coexistence"
      state_values: {N_prey: "K*d/(c*b)", N_pred: "..."}
      jacobian_spectrum:
        eigenvalues: ["+iω", "-iω"]
        any_zero_real_part: true
      hyperbolicity:
        is_hyperbolic: false
        reason: "pure imaginary eigenvalues"
      stability_status: NONHYPERBOLIC_INCONCLUSIVE
      required_certificate:
        options:
          - lyapunov_function
          - center_manifold_reduction
          - normal_form_analysis
        provided: lyapunov_function
        certificate:
          V: "N_prey + N_pred - K*log(N_prey) - K*log(N_pred)"
          V_dot: "0 on the declared domain"
          citation: "Khalil, Nonlinear Systems 3rd ed §4.2"
        upgraded_status: VERIFIED
```

**Rules:**
- If the Jacobian spectrum has any zero-real-part eigenvalue
  (pure imaginary OR zero), `hyperbolicity.is_hyperbolic`
  must be false and `stability_status` must be
  `NONHYPERBOLIC_INCONCLUSIVE`.
- `NONHYPERBOLIC_INCONCLUSIVE` is distinct from
  `UNDETERMINED` (symbolic timeout) and from `NOT_ASSESSED`
  (zero declared fixed points). It specifically means
  "linearization is inconclusive at this point and a
  nonlinear certificate is required."
- To upgrade to `VERIFIED`, the entry must provide one of:
  (a) a Lyapunov function with `V_dot ≤ 0` on the domain,
  (b) a center-manifold reduction with the reduced dynamics'
  stability proven,
  (c) a normal-form analysis reducing to a textbook case,
  each with an explicit textbook/paper citation.
- The validator rejects entries with
  `hyperbolicity.is_hyperbolic: false` but no certificate.

The v5 Lotka-Volterra example in the spec text is updated to
use the Lyapunov function `V = N_prey + N_pred - K·log(N_prey)
- K·log(N_pred)` — this is the textbook certificate and the
framework's first example now demonstrates the chosen
resolution, as the board asked.

---

## C3 — Tensor rank consistency (DOV-DSL scope + separate obligation)

**Problem (v4):** pint handles scalar unit algebra but cannot
catch rank mismatches, index symmetry violations, or
contraction validity in tensor-valued exchanges. The FSI
stress-tensor example in v4 requires exactly this.

**v5 resolution — explicit scope + separate tensor obligation:**

### C3a — DOV-DSL dimensional checking is scalar-unit-only

v5 declares the scope explicitly in the DOV-DSL grammar spec:

> DOV-DSL dimensional checking via pint is **scalar-unit-only**.
> A relation between tensor-valued quantities must be
> decomposed into scalar invariants (traces, determinants,
> eigenvalues, norms) before entering a DOV-DSL inequality,
> OR the tensor relation must be recorded in the separate
> `tensor_rank_consistency` block (see C3b) and human-verified.

The parser rejects DOV-DSL inequalities containing tensor-
valued operands and routes the author to the tensor block.

### C3b — tensor_rank_consistency obligation

Every EWE entry that mentions a tensor-valued quantity in its
canonical_equation.variables block carries:

```yaml
tensor_rank_consistency:
  quantities:
    - name: sigma
      rank: 2
      index_structure: "sigma_ij"
      symmetry: symmetric      # or antisymmetric | none
      index_symmetry_check: "sp.simplify(sigma - sigma.T) == 0"
      contravariance: [0, 0]   # covariant indices
  exchange_relations:
    - name: "traction_continuity"
      statement: "t_i = sigma_ij * n_j"
      rank_check: "rank(t) == 1 AND rank(sigma) == 2 AND rank(n) == 1"
      contraction_valid: true
  human_verified: true
  verifier: "architect"
  citation: "Landau-Lifshitz Theory of Elasticity §1"
```

**Rules:**
- `tensor_rank_consistency` is required whenever any
  variable in `canonical_equation.variables` has `rank > 0`.
- Rank, index symmetry, and contraction validity are
  **architect-declared** with a citation to a textbook
  source. They are **not validator-enforced** — the
  validator checks presence of the block, but the
  mathematical content is human-verified.
- This maintains honesty about the automation boundary:
  full tensor-aware typing is out of scope for v5, and we
  do not claim to provide it.

### C3c — FSI example walkthrough

The fluid-structure interaction ECP entry in v5:

```yaml
composition_class:
  - CONSTITUTIVE_CLOSURE        # wetted geometry
  - INTER_DOMAIN_TRANSDUCTION   # interface stress/velocity port
composite_classification: true
per_piece:
  - piece: "wetted_geometry"
    class: CONSTITUTIVE_CLOSURE
  - piece: "interface_stress_velocity"
    class: INTER_DOMAIN_TRANSDUCTION
    dirac_structure:
      form: implicit_junction
      junction_type: one_junction
tensor_rank_consistency:
  quantities:
    - {name: sigma_f, rank: 2, symmetry: symmetric}
    - {name: sigma_s, rank: 2, symmetry: symmetric}
    - {name: n, rank: 1}
    - {name: v, rank: 1}
  exchange_relations:
    - name: "stress_continuity"
      statement: "sigma_f * n = sigma_s * n on the wetted surface"
      rank_check: "rank 1 on both sides"
      contraction_valid: true
    - name: "velocity_continuity"
      statement: "v_f = v_s on the wetted surface"
      rank_check: "rank 1 on both sides"
  human_verified: true
  citation: "Bungartz-Schäfer, Fluid-Structure Interaction (2006)"
```

---

## C4 — Pragmatic partition with explicit escape hatch

**Problem (v4):** I called the four-class classification a
"constructive proof of exhaustiveness" while the decision
tree itself had a Q4-NO → REJECTED branch — an internal
contradiction. A rejection bin is an admission that some
couplings fall outside the four classes, which means the
claim was not actually a proof of exhaustiveness but a
partition-of-known-cases with a fallback.

**v5 resolution — rename, downgrade, add schema:**

1. The word **"proof"** is removed from the exhaustiveness
   discussion throughout the spec. The claim is now
   **"pragmatically complete partition for known physics
   coupling modalities."**

2. The Q4-NO terminal (now Q5-NO with STOCHASTIC_COUPLING
   inserted) is renamed from `REJECTED` to `UNCLASSIFIED`,
   with a structured escape-hatch schema:

```yaml
composition_class: UNCLASSIFIED
unclassified_entry:
  free_form_description: |
    Non-locally-coupled integro-differential equation pair
    (e.g., Boltzmann collision integral + Poisson field).
    Does not fit conservation, closure, transduction, rate,
    or stochastic classes as defined.
  known_to_not_fit:
    - {class: CONSERVATION_BALANCE, reason: "..."}
    - {class: CONSTITUTIVE_CLOSURE, reason: "..."}
    - {class: INTER_DOMAIN_TRANSDUCTION, reason: "..."}
    - {class: RATE_COUPLING, reason: "..."}
    - {class: STOCHASTIC_COUPLING, reason: "..."}
  human_review_required: true
  proposed_reduction:
    target_class: null   # optional; if reducible, state how
    argument: null
  status: AWAITING_BOARD_REVIEW
```

3. `UNCLASSIFIED` entries are valid in the ledger but cannot
   reach `STABLE` status without a board review that either
   (a) accepts the entry as genuinely new and proposes a
   future sixth class, or (b) demonstrates a reduction to an
   existing class with a formal argument. This is the same
   4-phase board protocol used for EWE entries themselves.

4. The exhaustiveness discussion in the v5 spec now reads:

> The five classes (CONSERVATION_BALANCE, CONSTITUTIVE_
> CLOSURE, INTER_DOMAIN_TRANSDUCTION, RATE_COUPLING,
> STOCHASTIC_COUPLING) are **pragmatically complete for
> known physics coupling modalities**. They are NOT
> mathematically exhaustive over all possible information
> flows between equations — integro-differential couplings,
> variational constraints with global character, and
> couplings that emerge only under homogenization are
> examples of known residual cases. Such compositions are
> recorded as `UNCLASSIFIED` with a mandatory human-review
> flag and await board review before reaching STABLE status.

This matches what the framework actually delivers, and loses
nothing.

---

## C5 — Modulated Dirac singularity sets

**Problem (v4):** J(x) can be rank-deficient at gimbal-lock
configurations, parameter values where the constitutive map
degenerates, or isolated points where two ports collapse.
v4's numerical fallback would silently pass over a domain
containing such singularities because Latin-hypercube
sampling is unlikely to land exactly on them.

**v5 resolution — architect-declared singularity set:**

```yaml
dirac_structure:
  form: explicit_matrix
  J_sympy: "Matrix([[0, -cos(theta)*cos(phi)], ...])"
  state_symbols: [theta, phi]
  modulated: true
  singularities:
    declared: true
    set: "{(theta, phi) : cos(theta) == 0}"
    reason: "gimbal lock at theta = ±pi/2"
    citation: "Hughes, Spacecraft Attitude Dynamics §3.4"
    domain_treatment: exclude  # or verify_explicitly
    excluded_domain: "theta in (-pi/2 + epsilon, pi/2 - epsilon)"
  skew_symmetry_check:
    method: symbolic
    result: VERIFIED
  numerical_fallback:
    sample_domain: "theta in [-pi/2+0.01, pi/2-0.01], phi in [0, 2pi]"
    sample_count: 1000
    max_abs_violation: 2.1e-14
    status: VERIFIED_NUMERICALLY
    singularity_check: "all samples excluded from declared
                        singularity set"
```

**Rules:**
- Every `explicit_matrix` Dirac-structure entry must have a
  `singularities` block.
- `declared: false` means the architect asserts there are
  no singularities in the declared domain — this is a
  reviewable claim and the board can reject it.
- `declared: true` requires either
  `domain_treatment: exclude` with an `excluded_domain`
  declaration, or `domain_treatment: verify_explicitly` with
  a per-singularity limit analysis showing the behavior is
  well-defined.
- The numerical fallback's sampler is required to skip any
  point within the declared singularity set; a
  `singularity_check` record is emitted confirming no
  samples landed inside.
- Without a `singularities` block, the entry is rejected at
  ingest.

---

## Secondary: pde_kinetic_annex convergence as human-verified

**v4 claim:** the pde_kinetic_annex convergence obligation is
validator-checked on recorded grid-study output.

**v5 correction:** the validator checks presence of the
`truncation_obligation` field and the citation, but the
actual convergence verdict is **architect-declared with
citation, not validator-enforced**. Grid-refinement studies
involve judgment calls about what "converged" means (which
norm, which error metric, which observable) that are not
automatable in v5. The annex adds a `human_verified: true`
flag and a `verifier` field, matching the tensor_rank_
consistency block's honesty-about-automation pattern.

---

## Questions for the board (v5)

1. Does the STOCHASTIC_COUPLING class with Itô-isometry,
   filtration, and regularity postconditions close the
   stochastic gap? Is there a specific SDE example (McKean-
   Vlasov mean-field, Dean-Kawasaki, rough paths / fractional
   Brownian) that still falls outside even this class?
2. Is `NONHYPERBOLIC_INCONCLUSIVE` with the three-option
   certificate set (Lyapunov / center-manifold / normal-form)
   the right shape, or is a fourth option (numerical
   continuation with rigorous error bounds, interval
   arithmetic a la Arb) needed for cases where symbolic
   methods fail?
3. Is the tensor_rank_consistency block's
   `human_verified: true` the right pragmatic scope for v5,
   or should v5 attempt a minimal tensor-aware typing layer
   (at least rank and index symmetry) before build?
4. Is the UNCLASSIFIED escape hatch schema rich enough, or
   should it require more structured metadata (e.g., a
   mandatory "minimum working example" code snippet that
   exercises the coupling)?
5. Is the singularity-set protocol (architect-declared,
   domain-treatment = exclude or verify_explicitly) the
   right shape, or does the validator need to attempt
   automated singularity detection (via
   sp.solve(det(J) == 0)) as a sanity check against the
   architect's declaration?
6. Fatal flaws remaining: what should the board flag that
   v5 still misses before Phase 14 build begins?

Verdict requested: APPROVE / MODIFY / REJECT. v5's explicit
goal is APPROVE. The iteration log shows convergence:
  v1 → MODIFY (5 concerns, including non-technical ones)
  v2 → MODIFY (5 concerns, schema formalization)
  v3 → MODIFY (4 concerns, exhaustiveness + Dirac correctness)
  v4 → MODIFY (5 concerns, narrower technical gaps)
  v5 → ?       (addresses v4's exact 5 mods)

If v5 still falls short, the board is asked to rank the
remaining gaps by severity so v6 can prioritize correctly.
"""


def main() -> int:
    try:
        with AIConsensusBoard(include_grok=True) as board:
            print("Running 4-phase board review of EWE concept v5 "
                  "(Grok included, ~12 model calls, ~6-10 minutes)...")
            result = board.four_phase_query(
                query_id="ewe_concept_review_v5",
                review_subject=(
                    "v5 of the EWE/ECP/EOE/EMP structured knowledge "
                    "framework, addressing the 5 required "
                    "modifications from v4: STOCHASTIC_COUPLING as "
                    "5th ECP class with Itô-isometry postconditions, "
                    "NONHYPERBOLIC_INCONCLUSIVE fixed-point status "
                    "with Lyapunov/center-manifold/normal-form "
                    "certificates, tensor_rank_consistency obligation "
                    "block (human-verified) with DOV-DSL scalar-only "
                    "scoping, UNCLASSIFIED escape-hatch schema "
                    "replacing REJECTED and downgrading 'proof' to "
                    "'pragmatically complete partition', and "
                    "architect-declared singularity sets for "
                    "modulated Dirac structures"
                ),
                user_payload=_CONCEPT_V5,
                rubric_schema=DESIGN_RUBRIC_SCHEMA,
                personas=DESIGN_REVIEW_PERSONAS,
            )
    except AIBoardKeysMissing as exc:
        print(f"Board keys missing: {exc}", file=sys.stderr)
        return 2

    lines: list[str] = []
    lines.append("# EWE Concept Review v5 — 4-Phase Academic Protocol\n")
    lines.append(f"**Query:** `{result.query_id}`  ")
    lines.append(f"**Include Grok:** {result.include_grok}  ")
    lines.append(f"**Editor verdict:** `{result.editor.verdict}`\n")
    lines.append(f"**All responded (Phase A):** {getattr(result, 'all_responded_a', 'n/a')}  ")
    lines.append(f"**All responded (Phase B):** {getattr(result, 'all_responded_b', 'n/a')}\n")

    lines.append("## Phase C — Editor synthesis (binding)\n")
    if result.editor.error:
        lines.append(f"**Status:** editor call failed ({result.editor.error})\n")
    else:
        lines.append(f"**Verdict:** `{result.editor.verdict}`\n")
        lines.append(f"**Rationale:**\n\n{result.editor.rationale}\n")
        if result.editor.required_modifications:
            lines.append("**Required modifications:**")
            for m in result.editor.required_modifications:
                lines.append(f"- {m}")
            lines.append("")

    lines.append("## Phase B — Informed votes\n")
    for r in result.phase_b:
        lines.append(f"### {r.reviewer}\n")
        if r.error:
            lines.append(f"**Status:** Phase B failed ({r.error})\n")
            continue
        lines.append(f"**Verdict:** `{r.updated_verdict}`  ")
        lines.append(f"**Position change:** {r.position_change}  ")
        lines.append(f"**Headline:** {r.headline}\n")
        lines.append(f"**Response to peers:**\n\n{r.response_to_peers}\n")

    lines.append("## Phase A — Independent drafts\n")
    for r in result.phase_a:
        lines.append(f"### {r.reviewer}\n")
        if r.error:
            lines.append(f"**Status:** Phase A failed ({r.error})\n")
            continue
        coi = f"⚠ {r.coi_note}" if r.coi_declared else "no COI"
        lines.append(f"**COI:** {coi}  ")
        lines.append(f"**Verdict:** `{r.verdict}`  ")
        lines.append(f"**Headline:** {r.headline}\n")
        if r.strengths:
            lines.append("**Strengths:**")
            for s in r.strengths:
                lines.append(f"- {s}")
            lines.append("")
        if r.concerns:
            lines.append("**Concerns:**")
            for c in r.concerns:
                lines.append(f"- {c}")
            lines.append("")
        if r.required_modifications:
            lines.append("**Required modifications:**")
            for m in r.required_modifications:
                lines.append(f"- {m}")
            lines.append("")

    REVIEW_PATH.write_text("\n".join(lines) + "\n")
    print(f"Wrote {REVIEW_PATH}")
    print(f"Editor verdict: {result.editor.verdict}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
