"""Generate Jupyter notebooks for live-sensor equation verification.

Given an equation.yaml (or composite.yaml) and a sensor-binding
config, this module generates a complete Jupyter notebook that:

  1. Reads live sensor values from makau.ai via the bridge API
  2. Computes the equation's prediction from those values
  3. Computes the residual (prediction - measurement)
  4. Reports pass/fail with tolerance
  5. Generates a time-series comparison plot (if history available)

The generated notebook is a standard nbformat v4 JSON dict that
can be:
  - POSTed to makau.ai's /api/hequ/execute-notebook for remote execution
  - Saved locally and run with `jupyter nbconvert --execute`
  - Rendered on the hequ.ai website as a verification artifact

Usage:
    from framework.notebook_generator import generate_verification_notebook
    from framework.makau_bridge import MakauBridge

    nb = generate_verification_notebook(
        equation_id="EQ-FOURIER-HEAT",
        formula="k * (T_hot - T_cold) / L",
        bindings={
            "T_hot":  {"sensor_id": "temp-01", "unit": "K"},
            "T_cold": {"sensor_id": "temp-02", "unit": "K"},
        },
        constants={"k": 401.0, "L": 0.5},
        predicted_variable="q",
        predicted_unit="W/m^2",
        tolerance=0.05,
    )

    bridge = MakauBridge()
    result = bridge.execute_notebook(nb)
"""

from __future__ import annotations

from typing import Any, Dict, Optional


def _code_cell(source: str) -> Dict[str, Any]:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": source.strip(),
    }


def _md_cell(source: str) -> Dict[str, Any]:
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": source.strip(),
    }


def generate_verification_notebook(
    equation_id: str,
    formula: str,
    bindings: Dict[str, Dict[str, str]],
    constants: Dict[str, float],
    predicted_variable: str,
    predicted_unit: str = "",
    tolerance: float = 0.05,
    title: Optional[str] = None,
    makau_api_base: str = "https://makau.ai",
) -> Dict[str, Any]:
    """Generate a complete verification notebook.

    Args:
        equation_id: e.g. "EQ-FOURIER-HEAT"
        formula: sympy-parseable formula string, e.g. "k*(T_hot-T_cold)/L"
        bindings: {variable_name: {"sensor_id": "...", "unit": "..."}}
            for variables read from live sensors
        constants: {variable_name: value} for known constants
        predicted_variable: the output variable name
        predicted_unit: unit string for display
        tolerance: relative tolerance for pass/fail (0.05 = 5%)
        title: notebook title (defaults to equation_id)
        makau_api_base: makau.ai API base URL

    Returns:
        nbformat v4 notebook dict ready for execution or POST.
    """
    title = title or f"Live verification: {equation_id}"
    sensor_vars = list(bindings.keys())
    const_vars = list(constants.keys())
    all_vars = sensor_vars + const_vars

    cells = []

    # Title
    cells.append(_md_cell(f"# {title}\n\n"
        f"**Equation:** `{equation_id}`  \n"
        f"**Formula:** `{predicted_variable} = {formula}`  \n"
        f"**Tolerance:** {tolerance*100:.1f}%  \n"
        f"**Generated by:** hequ.ai notebook generator"))

    # Imports
    cells.append(_code_cell(
        "import json\n"
        "import urllib.request\n"
        "import sympy as sp\n"
        "from datetime import datetime, timezone\n"
        "print('hequ.ai live verification notebook')\n"
        f"print('Equation: {equation_id}')\n"
        f"print('Time:', datetime.now(timezone.utc).isoformat())"
    ))

    # Read sensors
    sensor_read_lines = [
        f"MAKAU_API = '{makau_api_base}'",
        "HEADERS = {",
        "    'X-Makau-Tenant': 'hequ',",
        "    'X-Makau-User': 'hequ-bridge',",
        "    'Content-Type': 'application/json',",
        "}",
        "",
        "def read_sensor(sensor_id):",
        "    url = f'{MAKAU_API}/api/hequ/sensors/{sensor_id}/latest'",
        "    req = urllib.request.Request(url, headers=HEADERS)",
        "    with urllib.request.urlopen(req, timeout=10) as resp:",
        "        return json.loads(resp.read())",
        "",
        "# Read live sensor values",
        "sensor_values = {}",
    ]
    for var_name, binding in bindings.items():
        sid = binding["sensor_id"]
        sensor_read_lines.append(
            f"sensor_values['{var_name}'] = "
            f"read_sensor('{sid}')['value']"
        )
        sensor_read_lines.append(
            f"print(f'{var_name} = {{sensor_values[\"{var_name}\"]}} "
            f"(from sensor {sid})')"
        )
    cells.append(_code_cell("\n".join(sensor_read_lines)))

    # Constants
    const_lines = ["# Known constants"]
    for var_name, value in constants.items():
        const_lines.append(f"{var_name} = {value}")
        const_lines.append(f"print(f'{var_name} = {value}')")
    cells.append(_code_cell("\n".join(const_lines)))

    # Compute prediction
    sym_decl = ", ".join(
        f"{v}" for v in all_vars
    )
    compute_lines = [
        "# Compute equation prediction from sensor + constant values",
        f"{sym_decl} = sp.symbols('{' '.join(all_vars)}', positive=True)",
        f"formula_expr = sp.sympify('{formula}')",
        "",
        "# Build substitution dict",
        "subs = {}",
    ]
    for var in sensor_vars:
        compute_lines.append(
            f"subs[{var}] = sensor_values['{var}']"
        )
    for var, val in constants.items():
        compute_lines.append(f"subs[{var}] = {val}")
    compute_lines.extend([
        "",
        "predicted = float(formula_expr.subs(subs).evalf())",
        f"print(f'Predicted {predicted_variable} = {{predicted:.6g}} {predicted_unit}')",
    ])
    cells.append(_code_cell("\n".join(compute_lines)))

    # Compare to measurement (if the predicted variable also has a sensor)
    cells.append(_md_cell(
        "## Verification result\n\n"
        "Compare the equation's prediction against the measured "
        "value (if a sensor is bound to the output variable) or "
        "report the prediction for manual comparison."
    ))

    verify_lines = [
        f"tolerance = {tolerance}",
        f"predicted_var = '{predicted_variable}'",
        f"predicted_val = predicted",
        "",
        "# Check if we have a sensor for the output variable",
        f"output_sensor = {json.dumps(bindings.get(predicted_variable, {}))}",
        "if output_sensor and output_sensor.get('sensor_id'):",
        "    measured_data = read_sensor(output_sensor['sensor_id'])",
        "    measured = measured_data['value']",
        "    residual = predicted - measured",
        "    rel_error = abs(residual) / (abs(measured) + 1e-30)",
        "    passed = rel_error <= tolerance",
        "    print(f'Measured {predicted_var} = {measured:.6g}')",
        "    print(f'Predicted {predicted_var} = {predicted_val:.6g}')",
        "    print(f'Residual = {residual:.6g}')",
        "    print(f'Relative error = {rel_error:.4e}')",
        "    print(f'Tolerance = {tolerance}')",
        "    status = 'PASS' if passed else 'FAIL'",
        "    print(f'Result: {status}')",
        "else:",
        "    print(f'No output sensor bound for {predicted_var}')",
        "    print(f'Predicted value: {predicted_val:.6g}')",
        "    print('Manual comparison required')",
    ]
    cells.append(_code_cell("\n".join(verify_lines)))

    # Summary
    cells.append(_md_cell(
        "## Provenance\n\n"
        f"- **Equation:** `{equation_id}`\n"
        f"- **Formula:** `{predicted_variable} = {formula}`\n"
        f"- **Sensor bindings:** {json.dumps({k: v['sensor_id'] for k, v in bindings.items()})}\n"
        f"- **Constants:** {json.dumps(constants)}\n"
        f"- **Tolerance:** {tolerance*100:.1f}%\n"
        "- **Generated by:** hequ.ai `framework/notebook_generator.py`\n"
        "- **Executed on:** makau.ai lab environment"
    ))

    # Assemble notebook
    import json  # for the provenance cell
    return {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {"name": "python", "version": "3.12"},
            "hequ_metadata": {
                "equation_id": equation_id,
                "formula": formula,
                "bindings": bindings,
                "constants": constants,
                "predicted_variable": predicted_variable,
                "tolerance": tolerance,
            },
        },
        "cells": cells,
    }


def generate_timeseries_notebook(
    equation_id: str,
    formula: str,
    bindings: Dict[str, Dict[str, str]],
    constants: Dict[str, float],
    predicted_variable: str,
    predicted_unit: str = "",
    since: str = "1h",
    title: Optional[str] = None,
    makau_api_base: str = "https://makau.ai",
) -> Dict[str, Any]:
    """Generate a notebook that compares equation predictions to
    a time series of sensor readings.

    Like generate_verification_notebook but reads history instead
    of latest, computes the prediction at each timestep, and
    generates a comparison plot.
    """
    title = title or f"Time-series verification: {equation_id}"
    cells = []

    cells.append(_md_cell(
        f"# {title}\n\n"
        f"**Equation:** `{equation_id}`  \n"
        f"**Formula:** `{predicted_variable} = {formula}`  \n"
        f"**Window:** last {since}  \n"
        f"**Generated by:** hequ.ai notebook generator"
    ))

    cells.append(_code_cell(
        "import json\n"
        "import urllib.request\n"
        "import sympy as sp\n"
        "import matplotlib\n"
        "matplotlib.use('Agg')\n"
        "import matplotlib.pyplot as plt\n"
        "from datetime import datetime, timezone\n"
        f"\nMAKAU_API = '{makau_api_base}'\n"
        "HEADERS = {\n"
        "    'X-Makau-Tenant': 'hequ',\n"
        "    'X-Makau-User': 'hequ-bridge',\n"
        "    'Content-Type': 'application/json',\n"
        "}\n"
        "\ndef read_history(sensor_id, since):\n"
        "    url = f'{MAKAU_API}/api/hequ/sensors/{sensor_id}/history?since={since}'\n"
        "    req = urllib.request.Request(url, headers=HEADERS)\n"
        "    with urllib.request.urlopen(req, timeout=30) as resp:\n"
        "        return json.loads(resp.read())\n"
    ))

    # Read histories
    history_lines = ["# Read sensor histories"]
    for var_name, binding in bindings.items():
        sid = binding["sensor_id"]
        history_lines.append(
            f"history_{var_name} = read_history('{sid}', '{since}')"
        )
        history_lines.append(
            f"print(f'{var_name}: {{len(history_{var_name})}} readings')"
        )
    cells.append(_code_cell("\n".join(history_lines)))

    # Compute predictions at each timestep and plot
    all_vars = list(bindings.keys()) + list(constants.keys())
    cells.append(_code_cell(
        f"# Compute prediction at each timestep\n"
        f"{', '.join(all_vars)} = sp.symbols('{' '.join(all_vars)}', positive=True)\n"
        f"formula_expr = sp.sympify('{formula}')\n"
        f"\n"
        f"# Use the first sensor's timestamps as the time axis\n"
        f"first_var = '{list(bindings.keys())[0]}'\n"
        f"timestamps = [r['timestamp'] for r in history_{list(bindings.keys())[0]}]\n"
        f"predictions = []\n"
        f"for i, ts in enumerate(timestamps):\n"
        f"    subs = {{}}\n"
        + "".join(
            f"    subs[{v}] = history_{v}[i]['value']\n"
            for v in bindings.keys()
        )
        + "".join(
            f"    subs[{v}] = {val}\n"
            for v, val in constants.items()
        )
        + f"    predictions.append(float(formula_expr.subs(subs).evalf()))\n"
        f"\n"
        f"print(f'Computed {{len(predictions)}} predictions')\n"
        f"print(f'Mean prediction: {{sum(predictions)/len(predictions):.6g}} {predicted_unit}')"
    ))

    cells.append(_code_cell(
        "# Plot\n"
        "fig, ax = plt.subplots(figsize=(10, 5))\n"
        "ax.plot(range(len(predictions)), predictions, 'b-', "
        "label='Equation prediction', linewidth=1.5)\n"
        f"ax.set_ylabel('{predicted_variable} ({predicted_unit})')\n"
        "ax.set_xlabel('Sample index')\n"
        f"ax.set_title('{title}')\n"
        "ax.legend()\n"
        "ax.grid(True, alpha=0.3)\n"
        "plt.tight_layout()\n"
        "plt.savefig('verification_plot.png', dpi=150)\n"
        "plt.show()\n"
        "print('Plot saved to verification_plot.png')"
    ))

    return {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {"name": "python", "version": "3.12"},
        },
        "cells": cells,
    }
